version: "3.9"

services:
  ticket_purchase_service:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - '8080:8080'
      - '9000:9000'
    links:
      - db-ticket-purchase
      - activemq-artemis
    environment:
      - QUARKUS_DATASOURCE_REACTIVE_URL=vertx-reactive:postgresql://db-ticket-purchase:5432/ticket_purchase
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
      - QUARKUS_MONGODB_DATABASE=ticketPurchase
      - QUARKUS_QPID_JMS_URL=amqp://activemq-artemis:5672
      - QUARKUS_QPID_JMS_USERNAME=quarkus
      - QUARKUS_QPID_JMS_PASSWORD=quarkus
    networks:
      - quarkus

  db-ticket-purchase:
    image: postgres
    container_name: "db-ticket-purchase"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ticket_purchase
    ports:
      - '5432:5432'
    networks:
      - quarkus

  activemq-artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.25
    container_name: activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"
    environment:
      - AMQ_USER=quarkus
      - AMQ_PASSWORD=quarkus
      - AMQ_EXTRA_ARGS=--relax-jolokia
    networks:
      - quarkus

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - quarkus

networks:
  quarkus:
    driver: bridge
