version: "3.9"

services:
  tickets_provider_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tickets_provider_service
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://db-ticket-purchase:27017/ticketPurchase
      - QUARKUS_MONGODB_DATABASE=ticketPurchase
      - QUARKUS_QPID_JMS_URL=amqp://activemq-artemis:5672
      - QUARKUS_QPID_JMS_USERNAME=quarkus
      - QUARKUS_QPID_JMS_PASSWORD=quarkus
    networks:
      - backend-network
    depends_on:
      - db-ticket-purchase
      - activemq-artemis
    ports:
      - "8084:8084" 

  db-ticket-purchase:
    image: mongo
    container_name: db-ticket-purchase
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network

  activemq-artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker:1.0.25
    container_name: activemq-artemis
    ports:
      - "61616:61616"
      - "8161:8161"
      - "5672:5672"
    environment:
      - AMQ_USER=quarkus
      - AMQ_PASSWORD=quarkus
      - AMQ_EXTRA_ARGS=--relax-jolokia
    networks:
      - backend-network

volumes:
  mongodb_data:

networks:
  backend-network:
    external: true
